version: 1.0.0.{build}

environment:
    BOOST_ROOT: "c:/projects/ethash/deps/boost"

os: Windows Server 2012 R2

clone_folder: c:\projects\ethash

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

# scripts to run before build
before_build:
    - echo "Downloading boost..."
    - mkdir c:\projects\ethash\deps
    - cd c:\projects\ethash\deps
    - curl -O https://build.ethdev.com/builds/windows-precompiled/boost.tar.gz
    - echo "Unzipping boost..."
    - 7z x boost.tar.gz > nul
    - 7z x boost.tar > nul
    - ls
    - echo "Running cmake..."
    - cd c:\projects\ethash
    - if %PLATFORM% == Win32 cmake .
    - if %PLATFORM% == x64 cmake -G "Visual Studio 12 2013 Win64" . 

build:
    project: ALL_BUILD.vcxproj      # path to Visual Studio solution or project

after_build:
    - echo "Running tests..."
    - cd c:\projects\ethash\test\c
    - ls
    - cd c:\projects\ethash\test\c\Debug
    - Test.exe
    - echo "Finished!"

